extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-maven
  container: maven
pipelines:
  pullRequest:
    build:
      steps:
        - sh: skaffold version
          name: skaffold-version
        - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
          name: container-build

  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        comment: so we can retrieve the version in later steps
    build:
      steps:
        - sh: skaffold version
          name: skaffold-version
        - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
          name: container-build
        - sh: jx step tag --version \$(cat ../../VERSION)
          name: tag-version
          comment: Let's create tag in Git
    promote:
      steps:
      - sh: jx step changelog --version v\$(cat ../../VERSION)
        name: changelog


